# Generated by Django 3.1.3 on 2024-06-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=100)),
                ('fast_charge', models.IntegerField()),
                ('normal_charge', models.IntegerField()),
                ('fast_cost', models.IntegerField()),
                ('normal_cost', models.IntegerField()),
                ('adrs', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=100)),
                ('fast_charge', models.IntegerField()),
                ('normal_charge', models.IntegerField()),
                ('fast_cost', models.IntegerField()),
                ('normal_cost', models.IntegerField()),
                ('adrs', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('dist', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
            ],
        ),
    ]
